export const SENTENCES = [
    "Biology explores the living world and its complexity.",
    "Cells are the basic unit of life.",
    "Evolution explains how species change over time.",
    "Genetics studies how traits are inherited.",
    "Ecology examines interactions between organisms and environment.",
    "DNA carries genetic information in living organisms.",
    "Photosynthesis converts light into energy for plants.",
    "The sun was already setting behind the mountains.",
    "She opened the window and let fresh air inside.",
    "Typing quickly requires both rhythm and accuracy.",
    "Small habits become powerful over long periods of time.",
    "The coffee smelled strong and slightly bitter.",
    "Rain tapped softly against the roof all evening.",
    "Modern computers process billions of operations each second.",
    "A calm workspace helps improve concentration.",
    "Learning happens faster through repetition and feedback.",
    "The keyboard lights faded slowly in the dark room.",
    "The train arrived earlier than expected this morning.",
    "People often underestimate the value of consistency.",
    "The library remained quiet throughout the afternoon.",
    "Programming teaches patience and problem solving skills.",
    "A single mistake can change the entire result.",
    "Music drifted softly through the crowded hallway.",
    "The storm clouds gathered near the coastline.",
    "Careful preparation reduces unnecessary stress later.",
    "The old wooden chair creaked with every movement.",
    "Technology continues evolving at a rapid pace.",
    "The notebook was filled with unfinished ideas.",
    "Everyone waited silently for the announcement to begin.",
    "A warm meal can improve someone's entire day.",
    "The monitor glowed brightly in the dark office.",
    "Reading daily helps improve vocabulary naturally.",
    "The mountain trail became steeper after the bridge.",
    "Practice matters more than motivation over time.",
    "Several birds circled above the empty parking lot.",
    "The restaurant smelled like garlic and roasted herbs.",
    "Cold wind swept across the quiet street.",
    "The engineer reviewed the design one final time.",
    "Most skills improve through repetition and correction.",
    "The elevator doors opened with a soft sound.",
    "A balanced routine helps maintain steady progress.",
    "The students hurried across campus before the rain.",
    "Fresh bread rested beside the kitchen window.",
    "The meeting lasted longer than anyone expected.",
    "Late night coding sessions can become exhausting.",
    "The candle flickered gently beside the bookshelf.",
    "Simple interfaces often create better user experiences.",
    "The cat stretched lazily across the warm floor.",
    "The river moved quietly through the forest.",
    "A reliable system prevents unnecessary confusion.",
    "The hallway lights turned off automatically at midnight.",
]
